version: '3.8'

services:
  # ReactJS web (client-side)
  presentation_layer:
    build:
      context: ./client
    image: juve-client_img
    container_name: juve-client_ctr
    ports:
      - "8000:8000"
    depends_on:
      - logic_layer
    networks:
      - presentation-logic-network

  # Back-End with Remote Database (server-side, including API and MongoDB Atlas)
  logic_layer:
    build:
      context: ./server
    image: juve-server_img
    container_name: juve_server
    # restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      # == MongoDB Atlas configuration ==
      DATABASE_CLIENT: mongo
      DATABASE_HOST: ${DATABASE_HOST:-localhost}
      DATABASE_SRV: ${DATABASE_SRV:-false}
      DATABASE_PORT: ${DATABASE_PORT:-27017}
      DATABASE_NAME: ${DATABASE_NAME:-strapi}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-strapi}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-strapi}
      DATABASE_SSL: ${DATABASE_SSL:-false}
      # AUTHENTICATION_DATABASE: admin
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:1337}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      # == Cloudinary configuration ==
      CLOUD_NAME: ${CLOUD_NAME}
      API_KEY: ${API_KEY}
      API_SECRET: ${API_SECRET}
    ports:
      - "1337:1337"
    networks:
      - presentation-logic-network

networks:
  presentation-logic-network:
